config/routes.rb
Rails.application.routes.draw do
  resources :buses

  root 'buses#index'
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  has_one :number_plate, dependent: :destroy
  has_one :vehicle_licence, dependent: :destroy

  has_many :photos, dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :number_plate
  accepts_nested_attributes_for :vehicle_licence
  accepts_nested_attributes_for :photos, reject_if: proc { |attrs| attrs['image'].blank? }, allow_destroy: true

  paginates_per 10
end

app/models/number_plate.rb
class NumberPlate < ActiveRecord::Base
  belongs_to :bus

  before_validation :check_case

  validates :series, presence: true
  validates :number, presence: true
  validates :region, presence: true, length: { in: 2..3 }

  def display
    "#{series.first}#{number}#{series[1..-1]} #{region}"
  end

  protected

  def check_case
    self.series = series.mb_chars.upcase.to_s
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bus

  validates :image, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/vehicle_licence.rb
class VehicleLicence < ActiveRecord::Base
  belongs_to :bus

  before_validation :check_case

  validates :digit_code, presence: true, length: { is: 2 }, numericality: { only_integer: true }
  validates :letter_code, presence: true, length: { is: 2 }
  validates :number, presence: true, length: { is: 6 }, numericality: { only_integer: true }
  validates :release_date, presence: true

  def display
    "#{digit_code} #{letter_code} #{number}"
  end

  protected

  def check_case
    self.letter_code = letter_code.mb_chars.upcase.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  def index
    @buses = Bus.all.page params[:page]
    @total = Bus.count
  end

  def new
    @bus = Bus.new
    @bus.build_number_plate
    @bus.build_vehicle_licence
    @bus.photos.new
  end

  def create
    bus = Bus.new(bus_params)
    if bus.save
      flash[:success] = t('flash_messages.create.success')
      redirect_to buses_path
    else
      @bus = bus
      @bus.photos.new
      render :new
    end
  end

  def edit
    @bus = Bus.find(params[:id])
    @bus.photos.new
  end

  def update
    bus = Bus.find(params[:id])

    if bus.update_attributes(bus_params)
      flash[:success] = t('flash_messages.update.success')
      redirect_to buses_path
    else
      @bus = bus
      render :edit
    end
  end

  def destroy
    bus = Bus.find(params[:id])

    if bus.destroy
      flash[:success] = t('flash_messages.destroy.success')
      redirect_to(:back)
    else
      render :index
    end
  end

  private

  def bus_params
    params.require(:bus).permit(:name,
                                photos_attributes: [:image, :_destroy, :id],
                                number_plate_attributes: [:series, :number, :region],
                                vehicle_licence_attributes: [:digit_code, :letter_code, :number, :release_date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_buses_error_messages.slim
- if @bus && @bus.errors.any?
  .alert.alert-danger
    = pluralize(@bus.errors.count, 'error')
    ul
      - @bus.errors.full_messages.each do |msg|
        li = msg

app/views/buses/_form.slim
= javascript_include_tag 'nested_form'

= simple_nested_form_for bus, html: { class: 'bus-form', multipart: true } do |f|
  .row
    .col-md-6
      .form-group
        = f.label t('bus.name')
        = f.text_field :name, class: 'form-control', placeholder: 'Higer'

      .form-group.number-plate-form
        = f.label t('number_plate.number_plate')
        = f.fields_for :number_plate do |number|
          = number.text_field :series, class: 'form-control', placeholder: 'ААА'
          = number.text_field :number, class: 'form-control', placeholder: '123'
          = number.text_field :region, class: 'form-control', placeholder: '116'

    .col-md-6
      .form-group.vehicle-licence-form
        = f.label t('vehicle_licence.vehicle_licence')
        = f.fields_for :vehicle_licence do |licence|
          = licence.text_field :digit_code, class: 'form-control', placeholder: '77'
          = licence.text_field :letter_code, class: 'form-control', placeholder: 'ТО'
          = licence.text_field :number, class: 'form-control', placeholder: '123456'

          .form-group
            = label_tag t('vehicle_licence.release_date')
            = licence.date_select :release_date

  .row
    - unless bus.photos.first.new_record?
      .image-block
        - bus.photos.each do |p|
          - unless p.new_record?
            .image-item
              .image
                = link_to(image_tag(p.image.url(:thumb)), p.image.url)
              span.label.label-xs.label-default
                = p.id


    = f.simple_fields_for :photos do |p|
      - if p.object.new_record?
        = p.file_field :image
      br
      span.label.label-xs.label-default
        = p.object.id
      = p.link_to_remove t('common.delete'), class: 'btn btn-xs btn-danger'
      - if p.object.new_record?
        = f.link_to_add t('common.new'), :photos, class: 'btn btn-xs btn-primary'

  .actions
    = f.submit t('common.save'), class: 'btn btn-success'
    = link_to t('common.back'), buses_path, class: 'btn btn-default'

app/views/buses/edit.slim
h2.text-center = t('common.edit')
= render partial: 'form', locals: { bus: @bus }

app/views/buses/index.slim
table.table.table-bordered.table-hover.bustable
  thead
    tr
      th #
      th = t('bus.name')
      th = t('number_plate.number_plate')
      th = t('vehicle_licence.vehicle_licence')
      th = t('vehicle_licence.release_date')
      th = t('bus.photo')
      th
        = link_to t('common.new'), new_bus_path, class: 'btn btn-primary'
  tbody
    - @buses.each do |bus|
      tr
        td = bus.id
        td = bus.name
        td = bus.number_plate.display
        td = bus.vehicle_licence.display
        td = bus.vehicle_licence.release_date.strftime("%d.%m.%Y")
        td
          = bus.photos.empty? ? '' : "&#10004;".html_safe
        td
          .actions
            = link_to t('common.edit'), edit_bus_path(bus), class: 'btn btn-sm btn-success'
            = link_to t('common.delete'), bus_path(bus), method: 'delete', class: 'btn btn-sm btn-danger'
    tr
      td
        = t('common.total')
        |:
        = @total

= paginate @buses

app/views/buses/new.slim
h2
= form_for @bus, html: { class: 'bus-form' } do |f|
  .form-group
    = f.label t('bus.name')
    = f.text_field :name, class: 'form-control', placeholder: 'Higer'

  .form-group
    = f.label t('number_plate.number_plate')
    = f.fields_for :number_plate do |number|
      = number.text_field :series, class: 'form-control', placeholder: 'ААА'
      = number.text_field :number, class: 'form-control', placeholder: '123'
      = number.text_field :region, class: 'form-control', placeholder: '116'

  .form-group
    = f.label t('vehicle_licence.vehicle_licence')
    = f.fields_for :vehicle_licence do |licence|
      = licence.text_field :digit_code, class: 'form-control', placeholder: '77'
      = licence.text_field :letter_code, class: 'form-control', placeholder: 'ТО'
      = licence.text_field :number, class: 'form-control', placeholder: '123456'

      .form-group
        = label_tag t('vehicle_licence.release_date')
        = licence.text_field :release_date, class: 'form-control', placeholder: '2016-01-01'

  = f.submit t('common.save'), class: 'btn btn-success'
  = link_to t('common.back'), buses_path, class: 'btn btn-default'

app/views/layouts/application.slim
doctype html
html
  head
    title
      = content_for(:title) ? yield(:title) : 'Buslist'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    header.page-header.navbar-default
      h1.text-center
        = link_to 'Buslist', root_path

    - unless flash.blank?
      - flash.each do |name, msg|
        - classname_end = ''
        - case name
        - when 'success' then classname_end += 'success'
        - when 'error' then classname_end += 'danger'
        - else classname_end += 'info'
        - classname = 'text-center alert alert-' + classname_end
        = content_tag :div, msg, class: classname, role: 'alert'

    = render partial: 'buses_error_messages'

    = yield

    footer.page-footer.text-center
      p
        small
          = '&copy;'.html_safe
          |
          = link_to "Project at GitHub", 'https://github.com/rgarifullin/buslist'